public Class AutoRabitTest
{
    public List<Account> CreateAccount(String s, String p)
    
    //Testing - 2nd test
    
    
    
    {

    List<Account> a = new list<Account>();
    List<Account> apples = new List<Account>();
        for(Account acc:a)
        {
            acc.Name=s;
            acc.phone=p;
            insert a;
System.debug('I am here2 ');
         }
            return a;
        
    
    
    
    
    
    
    
    
    
    }

}